project:
  type: website

website:
  title: "ISSS608 - Coursework Website for CHEOK EN QI"
  search: true

  navbar:
    background: "#2563eb"   
    foreground: "white"
    collapse-below: lg

    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "HE01"
            href: HE01.qmd
          - text: "HE02"
            href: HE02.qmd
          - text: "HE03"
            href: HE03.qmd
          - text: "HE04"
            href: HE04.qmd
          - text: "HE05"
            href: HE05.qmd
          - text: "HE06"
            href: HE06.qmd           
      - text: "Take-home Exercises"
        menu:
          - text: "THE01"
            href: THE01.qmd            
        
    right:
      - icon: house
        href: index.qmd
        aria-label: Home
      - icon: person-circle
        href: about.qmd
        aria-label: About
      - icon: github
        href: "https://github.com/cheokenqi97"
        aria-label: GitHub

  page-footer:
    left: "Made with Quarto ✨"
    right: "ISSS608"
 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "On this page"
    toc-depth: 2
    smooth-scroll: true

editor: visual
